module : multiclass_classifier.MultiClassClassification
dataset : BoneClassification.BoneClassificationDb
model : resnet.ResNet
data_root : /data/Chrissi_US_augmentation/BoneClassification/
num_workers : 6
batch_size : 5
log_every_n_steps : 30
learning_rate : 0.01
min_epochs : 50
max_epochs : 300
input_channels : 1
gpus : 0
early_stopping_metric : val_loss
augmentation_mode : 'classical'
m_reflection_prob : 0.25
deformation_prob : 0.25
tilting_prob : 0.25
noise_prob : 0.25
classical_prob : 0.3
num_target_classes : 2
image_width: 272
image_height: 503