module : cut_module.CUT2D
datamodule : folder_split.FolderSplit
dataset : sweep_unpaired.SweepUnpaired
data_root : data/US2CT_SweepUnpaired
output_path : ./results
num_workers : 0
batch_size : 2
log_every_n_steps : 10
learning_rate : 0.0002
min_epochs : 1
max_epochs : 200
input_nc : 5
output_nc: 5
gpus : 0
load_size: 256
crop_size: 256
project_name: 'test'
group_name: 'test1'
