module : gan_image_generation.GanImageGeneration
dataset : BonePixelwiseDb.SubjectSplitDb
paired_db: True
model : pix2pix.Pix2PixModel
data_root : datasets/bones
output_path : ./results
num_workers : 4
batch_size : 3
log_every_n_steps : 10
learning_rate : 0.0002
min_epochs : 1
max_epochs : 200
input_nc : 1
output_nc: 1
gpus : 0
load_size: 512
crop_size: 512
group_name: 'Label2US'
