module : gan_semi_unpaired.GanSemiUnpairedModule
dataset : BonePixelwiseDb.MixedDb
model : pix2pix.Pix2PixModel
data_root : ./datasets
train_folders: 'CT_cropped_mask, US_convex'
val_folders: 'CT_cropped_mask'
test_folders: 'CT_cropped_mask'
output_path : ./results
num_workers : 0
batch_size : 3
log_every_n_steps : 10
learning_rate : 0.0002
min_epochs : 1
max_epochs : 200
input_nc : 1
output_nc: 1
gpus : 0
load_size: 512
crop_size: 512
group_name: 'test_visual'
project_name: 'test_project'
