module : gan_image_generation.GanImageGeneration
dataset : PairedPixelwiseDb.SubjectSplitDb
model : pix2pix.Pix2PixModel
data_root : datasets/manual_seg
random_split : '80_20'
output_path : ./results
num_workers : 4
batch_size : 4
log_every_n_steps : 10
learning_rate : 0.0002
min_epochs : 1
max_epochs : 100
input_nc : 1
output_nc: 1
gpus : 0